version: 2

project_name: acmehub-cli

git:
  tag_sort: -version:refname
  prerelease_suffix: "-"

builds:
  - main: ./main.go
    binary: acmehub-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/geektr-cloud/acme-hub/integrations/acmehub-cli/cmd.version={{trimPrefix .Tag "integrations/acmehub-cli/"}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

release:
  name_template: "acmehub-cli {{trimPrefix .Tag \"integrations/acmehub-cli/\"}}"

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"
