apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "acmehub-syncer.fullname" . }}
  namespace: {{ .Values.clusterResourceNamespace }}
  labels:
    {{- include "acmehub-syncer.labels" . | nindent 4 }}
